onyxia:
  ingress:
    enabled: true
    ingressClassName: "nginx"
    annotations:
      kubernetes.io/ingress.class: nginx
    hosts:
      - host: onyxia.localhost
  web:
    env:
      #GLOBAL_ALERT: |
      #  {
      #    severity: "success",
      #    message: {
      #      en: "A **big** announcement! [Check it out](https://example.com)!",
      #      fr: "Une annonce **importante**! [Regardez](https://example.com)!"
      #    }
      #  }
  api:
    regions: [
      {
        id: "my-region",
        name: "My Region",
        description: "Region hosted on my-cluster",
        services: {
          type: "KUBERNETES",
          singleNamespace: true,
          authenticationMode: "serviceAccount",
          expose: {
            domain: "localhost"
          }
        }
      }
    ]

    # add configmap with zscaler certs as volume to api pod
    extraVolumes:
      - name: zscaler-certs
        configMap:
          name: zscaler-certs

    # mount the zscaler certs volume to relevant locations in api container
    extraVolumeMounts:
      - name: zscaler-certs
        mountPath: /usr/local/share/ca-certificates
      - name: zscaler-certs
        subPath: zscaler_root_ca.crt
        mountPath: /etc/ssl/certs/zscaler_root_ca.crt
      - name: zscaler-certs
        subPath: zscaler_intermediate_root_ca.crt
        mountPath: /etc/ssl/certs/zscaler_intermediate_root_ca.crt